<#assign

l_contact_information = "contact information" <#--35912906--> <#--联系人信息-->
l_team_member_information_template_file = "Team member information template file" <#--47752701--> <#--团队成员信息模板文件-->
l_apply_terms = "Apply terms" <#--13489805--> <#--报名条款-->
l_mobile_phone = "mobile phone" <#--83042161--> <#--手机号码-->
l_sms_verification_code = "SMS verification code" <#--40237065--> <#--手机验证码-->
l_number_of_team_members = "Number of team members" <#--33843436--> <#--参加的团队人数-->
l_team_member_information = "Team member information" <#--10473574--> <#--团队成员信息-->
l_create_a_name_for_your_team. = "Create a name for your team." <#--79998304--> <#--为你的团队取个名字吧-->
l_second_step = "Second step" <#--9166647--> <#--第二步-->
l_people = "people" <#--94608188--> <#--人-->
l_please_pay_attention_to_the_sms_messages_and_accurately_fill_the_applicant_information = "Please pay attention to the SMS messages and accurately fill the applicant information" <#--86366046--> <#--请留意手机短信并准确填写报名人信息-->
l_people_at_least = "people at least" <#--49877199--> <#--人以上-->
l_applicant_information = "Applicant information" <#--4650206--> <#--报名人信息-->
l_apply_attachment = "Apply attachment" <#--70427016--> <#--报名附件-->
l_team_name = "Team name" <#--65673118--> <#--团队名称-->
l_contact_name = "Contact name" <#--45397164--> <#--联系人姓名-->
l_other_information = "Other information" <#--55424963--> <#--其他信息-->
l_please_enter_sms_verification_code = "Please enter SMS verification code" <#--56982783--> <#--请输入手机验证码-->
l_click_here_to_download_the_member_information_template_file = "Click here to download the member information template file" <#--58492928--> <#--点击这里下载成员信息文件模板-->
l_i_have_read_and_agreed = "I have read and agreed" <#--56281568--> <#--我已阅读并同意-->
l_first_step = "First step" <#--52878640--> <#--第一步-->
l_send_verification_code = "Send verification code" <#--48648104--> <#--获取验证码-->
l_upload_member_information_file = "Upload member information file" <#--18978811--> <#--上传成员信息文件-->
l_number_range_of_team_members = "Number range of team members" <#--14353425--> <#--团队报名人数范围为-->
l_event_apply = "Event apply" <#--49910837--> <#--活动报名-->
l_order_remark = "Order remark" <#--51028417--> <#--订单备注-->
l_characters = "characters" <#--14248226--> <#--个字符-->
l_upload_attachment = "Upload attachment" <#--43467565--> <#--上传附件-->
l_forth_step = "Forth step" <#--98722389--> <#--第四步-->
l_range = "Range" <#--91254718--> <#--范围-->
l_characters_of_mobile_phone = "characters of mobile phone" <#--74424687--> <#--位手机号码-->
l_in_order_to_process_all_procedures_and_purchase_insurance = "In order to process all procedures and purchase insurance" <#--870402--> <#--以便办理各种手续和购买保险-->
l_third_step = "Third step" <#--19756461--> <#--第三步-->
l_upload_attachment = "Upload attachment" <#--15040517--> <#--添加附件-->
l_please_input = "Please input" <#--31617818--> <#--请输入-->
l_event's_relevant_notification_will_be_sent_to_the_contact = "Event's relevant notification will be sent to the contact" <#--78655094--> <#--本活动的相关通知会通知联系人-->
>